
public class CatchingExeptions {

	public static void main(String[] args) {
		
		try {
			int[] a = new int[2];
			
			a[0] = 1;
			
		} catch (ArrayIndexOutOfBoundsException exception) {
			System.out.println("Достъп до несъществуващ индекс");
		} catch (ArithmeticException exception){
			System.out.println("Невъзможно делене на нула");
		} catch (Exception exception){
			System.out.println("Друга грешка");
		}

	}

}
