
public class CatchingExeptions {

	public static void main(String[] args) {
		
		try {
			intp[] a = new int[2];
		} catch (ArrayIndexOutOfBoundsException exception) {
			System.out.println("Достъп до несъществуващ индекс");
		} catch (ArithmeticException exception){
			System.out.println("Невъзможно делене на нула");
		} catch (Exception exception){
			System.out.println("Друга грешка");
		}

	}

}
